
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : Thursday, October 18, 2007
	Important: Do not modify this file. Edit the file SqlPaymentSettingProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using ZNode.Libraries.DataAccess.Entities;
using ZNode.Libraries.DataAccess.Data;
using ZNode.Libraries.DataAccess.Data.Bases;

#endregion

namespace ZNode.Libraries.DataAccess.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="PaymentSetting"/> entity.
	///</summary>
	public partial class SqlPaymentSettingProviderBase : PaymentSettingProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlPaymentSettingProviderBase"/> instance.
		/// </summary>
		public SqlPaymentSettingProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlPaymentSettingProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we use the stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlPaymentSettingProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="paymentSettingID">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Int32 paymentSettingID)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@PaymentSettingID", DbType.Int32, paymentSettingID);
			
			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(PaymentSetting)
					,paymentSettingID);
				EntityManager.StopTracking(entityKey);
			}
			
			if (results == 0)
			{
				//throw new DataException("The record has been already deleted.");
				return false;
			}
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereclause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND)</remarks>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@PaymentSettingID", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@PaymentTypeID", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ProfileID", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@GatewayTypeID", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@GatewayUsername", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@GatewayPassword", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@EnableVisa", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@EnableMasterCard", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@EnableAmex", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@EnableDiscover", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TransactionKey", DbType.AnsiString, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ActiveInd", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@DisplayOrder", DbType.Byte, DBNull.Value);
		database.AddInParameter(commandWrapper, "@TestMode", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@OfflineMode", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@SaveCreditCartInfo", DbType.Boolean, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("paymentsettingid ") || clause.Trim().StartsWith("paymentsettingid="))
				{
					database.SetParameterValue(commandWrapper, "@PaymentSettingID", 
						clause.Replace("paymentsettingid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("paymenttypeid ") || clause.Trim().StartsWith("paymenttypeid="))
				{
					database.SetParameterValue(commandWrapper, "@PaymentTypeID", 
						clause.Replace("paymenttypeid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("profileid ") || clause.Trim().StartsWith("profileid="))
				{
					database.SetParameterValue(commandWrapper, "@ProfileID", 
						clause.Replace("profileid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("gatewaytypeid ") || clause.Trim().StartsWith("gatewaytypeid="))
				{
					database.SetParameterValue(commandWrapper, "@GatewayTypeID", 
						clause.Replace("gatewaytypeid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("gatewayusername ") || clause.Trim().StartsWith("gatewayusername="))
				{
					database.SetParameterValue(commandWrapper, "@GatewayUsername", 
						clause.Replace("gatewayusername","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("gatewaypassword ") || clause.Trim().StartsWith("gatewaypassword="))
				{
					database.SetParameterValue(commandWrapper, "@GatewayPassword", 
						clause.Replace("gatewaypassword","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("enablevisa ") || clause.Trim().StartsWith("enablevisa="))
				{
					database.SetParameterValue(commandWrapper, "@EnableVisa", 
						clause.Replace("enablevisa","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("enablemastercard ") || clause.Trim().StartsWith("enablemastercard="))
				{
					database.SetParameterValue(commandWrapper, "@EnableMasterCard", 
						clause.Replace("enablemastercard","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("enableamex ") || clause.Trim().StartsWith("enableamex="))
				{
					database.SetParameterValue(commandWrapper, "@EnableAmex", 
						clause.Replace("enableamex","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("enablediscover ") || clause.Trim().StartsWith("enablediscover="))
				{
					database.SetParameterValue(commandWrapper, "@EnableDiscover", 
						clause.Replace("enablediscover","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("transactionkey ") || clause.Trim().StartsWith("transactionkey="))
				{
					database.SetParameterValue(commandWrapper, "@TransactionKey", 
						clause.Replace("transactionkey","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("activeind ") || clause.Trim().StartsWith("activeind="))
				{
					database.SetParameterValue(commandWrapper, "@ActiveInd", 
						clause.Replace("activeind","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("displayorder ") || clause.Trim().StartsWith("displayorder="))
				{
					database.SetParameterValue(commandWrapper, "@DisplayOrder", 
						clause.Replace("displayorder","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("testmode ") || clause.Trim().StartsWith("testmode="))
				{
					database.SetParameterValue(commandWrapper, "@TestMode", 
						clause.Replace("testmode","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("offlinemode ") || clause.Trim().StartsWith("offlinemode="))
				{
					database.SetParameterValue(commandWrapper, "@OfflineMode", 
						clause.Replace("offlinemode","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("savecreditcartinfo ") || clause.Trim().StartsWith("savecreditcartinfo="))
				{
					database.SetParameterValue(commandWrapper, "@SaveCreditCartInfo", 
						clause.Replace("savecreditcartinfo","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
	
				
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();				
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> Find(TransactionManager transactionManager, SqlFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Find_Dynamic", typeof(PaymentSettingColumn), parameters, orderBy, start, pageLength);
			
			if ( parameters != null )
			{
				SqlFilterParameter param;

				for ( int i = 0; i < parameters.Count; i++ )
				{
					param = parameters[i];
					database.AddInParameter(commandWrapper, param.Name, param.DbType, param.Value);
				}
			}

			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			IDataReader reader = null;
			
			try
			{
				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if ( reader != null )
					reader.Close();
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetPaged", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions

		#region GetByGatewayTypeID
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_SC_PaymentSetting_SC_Gateway key.
		///		FK_SC_PaymentSetting_SC_Gateway Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="gatewayTypeID"></param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetByGatewayTypeID(TransactionManager transactionManager, System.Int32? gatewayTypeID, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetByGatewayTypeID", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@GatewayTypeID", DbType.Int32, gatewayTypeID);
			
			IDataReader reader = null;
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
			
				//Create Collection
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}	
		#endregion
	

		#region GetByPaymentTypeID
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_SC_PaymentSetting_SC_PaymentType key.
		///		FK_SC_PaymentSetting_SC_PaymentType Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="paymentTypeID"></param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of ZNode.Libraries.DataAccess.Entities.PaymentSetting objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetByPaymentTypeID(TransactionManager transactionManager, System.Int32 paymentTypeID, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetByPaymentTypeID", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@PaymentTypeID", DbType.Int32, paymentTypeID);
			
			IDataReader reader = null;
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> rows = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
			
				//Create Collection
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}	
		#endregion
	
	#endregion
	
		#region Get By Index Functions

		#region GetByPaymentSettingID
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_SC_PaymentSetting index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="paymentSettingID"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <returns>Returns an instance of the <see cref="ZNode.Libraries.DataAccess.Entities.PaymentSetting"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.PaymentSetting GetByPaymentSettingID(TransactionManager transactionManager, System.Int32 paymentSettingID, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetByPaymentSettingID", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@PaymentSettingID", DbType.Int32, paymentSettingID);
			
			IDataReader reader = null;
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> tmp = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion


		#region GetByProfileIDPaymentTypeID
					
		/// <summary>
		/// 	Gets rows from the datasource based on the IX1 index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="profileID"></param>
		/// <param name="paymentTypeID"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <returns>Returns an instance of the <see cref="ZNode.Libraries.DataAccess.Entities.TList&lt;PaymentSetting&gt;"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetByProfileIDPaymentTypeID(TransactionManager transactionManager, System.Int32 profileID, System.Int32 paymentTypeID, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetByProfileIDPaymentTypeID", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@ProfileID", DbType.Int32, profileID);
				database.AddInParameter(commandWrapper, "@PaymentTypeID", DbType.Int32, paymentTypeID);
			
			IDataReader reader = null;
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> tmp = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			
			return tmp;
			
			//return rows;
		}
		
		#endregion


		#region GetByProfileID
					
		/// <summary>
		/// 	Gets rows from the datasource based on the ix2 index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="profileID"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <returns>Returns an instance of the <see cref="ZNode.Libraries.DataAccess.Entities.TList&lt;PaymentSetting&gt;"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> GetByProfileID(TransactionManager transactionManager, System.Int32 profileID, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_GetByProfileID", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@ProfileID", DbType.Int32, profileID);
			
			IDataReader reader = null;
			ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting> tmp = new ZNode.Libraries.DataAccess.Entities.TList<PaymentSetting>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			
			return tmp;
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk many entity to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the ZNode.Libraries.DataAccess.Entities.PaymentSetting object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<ZNode.Libraries.DataAccess.Entities.PaymentSetting> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "ZNodePaymentSetting";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("PaymentSettingID", typeof(System.Int32));
			col0.AllowDBNull = false;		
			DataColumn col1 = dataTable.Columns.Add("PaymentTypeID", typeof(System.Int32));
			col1.AllowDBNull = false;		
			DataColumn col2 = dataTable.Columns.Add("ProfileID", typeof(System.Int32));
			col2.AllowDBNull = false;		
			DataColumn col3 = dataTable.Columns.Add("GatewayTypeID", typeof(System.Int32));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("GatewayUsername", typeof(System.String));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("GatewayPassword", typeof(System.String));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("EnableVisa", typeof(System.Boolean));
			col6.AllowDBNull = true;		
			DataColumn col7 = dataTable.Columns.Add("EnableMasterCard", typeof(System.Boolean));
			col7.AllowDBNull = true;		
			DataColumn col8 = dataTable.Columns.Add("EnableAmex", typeof(System.Boolean));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("EnableDiscover", typeof(System.Boolean));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("TransactionKey", typeof(System.String));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("ActiveInd", typeof(System.Boolean));
			col11.AllowDBNull = false;		
			DataColumn col12 = dataTable.Columns.Add("DisplayOrder", typeof(System.Byte));
			col12.AllowDBNull = false;		
			DataColumn col13 = dataTable.Columns.Add("TestMode", typeof(System.Boolean));
			col13.AllowDBNull = false;		
			DataColumn col14 = dataTable.Columns.Add("OfflineMode", typeof(System.Boolean));
			col14.AllowDBNull = true;		
			DataColumn col15 = dataTable.Columns.Add("SaveCreditCartInfo", typeof(System.Boolean));
			col15.AllowDBNull = true;		
			
			bulkCopy.ColumnMappings.Add("PaymentSettingID", "PaymentSettingID");
			bulkCopy.ColumnMappings.Add("PaymentTypeID", "PaymentTypeID");
			bulkCopy.ColumnMappings.Add("ProfileID", "ProfileID");
			bulkCopy.ColumnMappings.Add("GatewayTypeID", "GatewayTypeID");
			bulkCopy.ColumnMappings.Add("GatewayUsername", "GatewayUsername");
			bulkCopy.ColumnMappings.Add("GatewayPassword", "GatewayPassword");
			bulkCopy.ColumnMappings.Add("EnableVisa", "EnableVisa");
			bulkCopy.ColumnMappings.Add("EnableMasterCard", "EnableMasterCard");
			bulkCopy.ColumnMappings.Add("EnableAmex", "EnableAmex");
			bulkCopy.ColumnMappings.Add("EnableDiscover", "EnableDiscover");
			bulkCopy.ColumnMappings.Add("TransactionKey", "TransactionKey");
			bulkCopy.ColumnMappings.Add("ActiveInd", "ActiveInd");
			bulkCopy.ColumnMappings.Add("DisplayOrder", "DisplayOrder");
			bulkCopy.ColumnMappings.Add("TestMode", "TestMode");
			bulkCopy.ColumnMappings.Add("OfflineMode", "OfflineMode");
			bulkCopy.ColumnMappings.Add("SaveCreditCartInfo", "SaveCreditCartInfo");
			
			foreach(ZNode.Libraries.DataAccess.Entities.PaymentSetting entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["PaymentSettingID"] = entity.PaymentSettingID;
							
				
					row["PaymentTypeID"] = entity.PaymentTypeID;
							
				
					row["ProfileID"] = entity.ProfileID;
							
				
					row["GatewayTypeID"] = entity.GatewayTypeID.HasValue ? (object) entity.GatewayTypeID  : System.DBNull.Value;
							
				
					row["GatewayUsername"] = entity.GatewayUsername;
							
				
					row["GatewayPassword"] = entity.GatewayPassword;
							
				
					row["EnableVisa"] = entity.EnableVisa.HasValue ? (object) entity.EnableVisa  : System.DBNull.Value;
							
				
					row["EnableMasterCard"] = entity.EnableMasterCard.HasValue ? (object) entity.EnableMasterCard  : System.DBNull.Value;
							
				
					row["EnableAmex"] = entity.EnableAmex.HasValue ? (object) entity.EnableAmex  : System.DBNull.Value;
							
				
					row["EnableDiscover"] = entity.EnableDiscover.HasValue ? (object) entity.EnableDiscover  : System.DBNull.Value;
							
				
					row["TransactionKey"] = entity.TransactionKey;
							
				
					row["ActiveInd"] = entity.ActiveInd;
							
				
					row["DisplayOrder"] = entity.DisplayOrder;
							
				
					row["TestMode"] = entity.TestMode;
							
				
					row["OfflineMode"] = entity.OfflineMode.HasValue ? (object) entity.OfflineMode  : System.DBNull.Value;
							
				
					row["SaveCreditCartInfo"] = entity.SaveCreditCartInfo.HasValue ? (object) entity.SaveCreditCartInfo  : System.DBNull.Value;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(ZNode.Libraries.DataAccess.Entities.PaymentSetting entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a ZNode.Libraries.DataAccess.Entities.PaymentSetting object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">ZNode.Libraries.DataAccess.Entities.PaymentSetting object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the ZNode.Libraries.DataAccess.Entities.PaymentSetting object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, ZNode.Libraries.DataAccess.Entities.PaymentSetting entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Insert", _useStoredProcedure);
			
			database.AddOutParameter(commandWrapper, "@PaymentSettingID", DbType.Int32, 4);
			database.AddInParameter(commandWrapper, "@PaymentTypeID", DbType.Int32, entity.PaymentTypeID );
			database.AddInParameter(commandWrapper, "@ProfileID", DbType.Int32, entity.ProfileID );
			database.AddInParameter(commandWrapper, "@GatewayTypeID", DbType.Int32, (entity.GatewayTypeID.HasValue ? (object) entity.GatewayTypeID  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@GatewayUsername", DbType.AnsiString, entity.GatewayUsername );
			database.AddInParameter(commandWrapper, "@GatewayPassword", DbType.AnsiString, entity.GatewayPassword );
			database.AddInParameter(commandWrapper, "@EnableVisa", DbType.Boolean, (entity.EnableVisa.HasValue ? (object) entity.EnableVisa  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@EnableMasterCard", DbType.Boolean, (entity.EnableMasterCard.HasValue ? (object) entity.EnableMasterCard  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@EnableAmex", DbType.Boolean, (entity.EnableAmex.HasValue ? (object) entity.EnableAmex  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@EnableDiscover", DbType.Boolean, (entity.EnableDiscover.HasValue ? (object) entity.EnableDiscover  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@TransactionKey", DbType.AnsiString, entity.TransactionKey );
			database.AddInParameter(commandWrapper, "@ActiveInd", DbType.Boolean, entity.ActiveInd );
			database.AddInParameter(commandWrapper, "@DisplayOrder", DbType.Byte, entity.DisplayOrder );
			database.AddInParameter(commandWrapper, "@TestMode", DbType.Boolean, entity.TestMode );
			database.AddInParameter(commandWrapper, "@OfflineMode", DbType.Boolean, (entity.OfflineMode.HasValue ? (object) entity.OfflineMode  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@SaveCreditCartInfo", DbType.Boolean, (entity.SaveCreditCartInfo.HasValue ? (object) entity.SaveCreditCartInfo  : System.DBNull.Value));
			
			int results = 0;
			
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					

			entity.PaymentSettingID = (System.Int32) database.GetParameterValue(commandWrapper, "@PaymentSettingID");						
			
			
			entity.AcceptChanges();
	
			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">ZNode.Libraries.DataAccess.Entities.PaymentSetting object to update.</param>
		/// <remarks>
		///		After updating the datasource, the ZNode.Libraries.DataAccess.Entities.PaymentSetting object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, ZNode.Libraries.DataAccess.Entities.PaymentSetting entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ZNODE_NT_ZNodePaymentSetting_Update", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@PaymentSettingID", DbType.Int32, entity.PaymentSettingID );
			database.AddInParameter(commandWrapper, "@PaymentTypeID", DbType.Int32, entity.PaymentTypeID );
			database.AddInParameter(commandWrapper, "@ProfileID", DbType.Int32, entity.ProfileID );
			database.AddInParameter(commandWrapper, "@GatewayTypeID", DbType.Int32, (entity.GatewayTypeID.HasValue ? (object) entity.GatewayTypeID : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@GatewayUsername", DbType.AnsiString, entity.GatewayUsername );
			database.AddInParameter(commandWrapper, "@GatewayPassword", DbType.AnsiString, entity.GatewayPassword );
			database.AddInParameter(commandWrapper, "@EnableVisa", DbType.Boolean, (entity.EnableVisa.HasValue ? (object) entity.EnableVisa : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@EnableMasterCard", DbType.Boolean, (entity.EnableMasterCard.HasValue ? (object) entity.EnableMasterCard : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@EnableAmex", DbType.Boolean, (entity.EnableAmex.HasValue ? (object) entity.EnableAmex : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@EnableDiscover", DbType.Boolean, (entity.EnableDiscover.HasValue ? (object) entity.EnableDiscover : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@TransactionKey", DbType.AnsiString, entity.TransactionKey );
			database.AddInParameter(commandWrapper, "@ActiveInd", DbType.Boolean, entity.ActiveInd );
			database.AddInParameter(commandWrapper, "@DisplayOrder", DbType.Byte, entity.DisplayOrder );
			database.AddInParameter(commandWrapper, "@TestMode", DbType.Boolean, entity.TestMode );
			database.AddInParameter(commandWrapper, "@OfflineMode", DbType.Boolean, (entity.OfflineMode.HasValue ? (object) entity.OfflineMode : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@SaveCreditCartInfo", DbType.Boolean, (entity.SaveCreditCartInfo.HasValue ? (object) entity.SaveCreditCartInfo : System.DBNull.Value) );
			
			int results = 0;
			
			
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
				EntityManager.StopTracking(entity.EntityTrackingKey);
			
			
			entity.AcceptChanges();
	
			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	
		#endregion
	}//end class
} // end namespace
