	
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Thursday, October 18, 2007
	Important: Do not modify this file. Edit the file Category.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace ZNode.Libraries.DataAccess.Entities
{
	#region CategoryEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Category"/> object.
	/// </remarks>
	public class CategoryEventArgs : System.EventArgs
	{
		private CategoryColumn column;
		private object value;
		
		
		///<summary>
		/// Initalizes a new Instance of the CategoryEventArgs class.
		///</summary>
		public CategoryEventArgs(CategoryColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CategoryEventArgs class.
		///</summary>
		public CategoryEventArgs(CategoryColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		
		///<summary>
		/// The CategoryColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CategoryColumn" />
		public CategoryColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	
	///<summary>
	/// Define a delegate for all Category related events.
	///</summary>
	public delegate void CategoryEventHandler(object sender, CategoryEventArgs e);
	
	///<summary>
	/// An object representation of the 'ZNodeCategory' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	//[ToolboxItem(typeof(Category))]
	public abstract partial class CategoryBase : EntityBase, IEntityId<CategoryKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		/// 	Old the inner data of the entity.
		/// </summary>
		private CategoryEntityData entityData;
		
		// <summary>
		// 	Old the original data of the entity.
		// </summary>
		//CategoryEntityData originalData;
		
		/// <summary>
		/// 	Old a backup of the inner data of the entity.
		/// </summary>
		private CategoryEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		[NonSerialized]
		private TList<Category> parentCollection;
		private bool inTxn = false;

		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event CategoryEventHandler ColumnChanging;
		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CategoryEventHandler ColumnChanged;		
		#endregion "Variable Declarations"
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CategoryBase"/> instance.
		///</summary>
		public CategoryBase()
		{
			this.entityData = new CategoryEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CategoryBase"/> instance.
		///</summary>
		///<param name="categoryPortalID"></param>
		///<param name="categoryName"></param>
		///<param name="categoryTitle"></param>
		///<param name="categoryShortDescription"></param>
		///<param name="categoryDescription"></param>
		///<param name="categoryParentCategoryID"></param>
		///<param name="categoryDisplayOrder"></param>
		///<param name="categoryImageFile"></param>
		///<param name="categoryVisibleInd"></param>
		///<param name="categorySubCategoryGridVisibleInd"></param>
		///<param name="categorySEOTitle"></param>
		///<param name="categorySEOKeywords"></param>
		///<param name="categorySEODescription"></param>
		public CategoryBase(System.Int32 categoryPortalID, System.String categoryName, System.String categoryTitle, 
			System.String categoryShortDescription, System.String categoryDescription, System.Int32? categoryParentCategoryID, 
			System.Int32 categoryDisplayOrder, System.String categoryImageFile, System.Boolean categoryVisibleInd, 
			System.Boolean categorySubCategoryGridVisibleInd, System.String categorySEOTitle, System.String categorySEOKeywords, 
			System.String categorySEODescription)
		{
			this.entityData = new CategoryEntityData();
			this.backupData = null;

			this.PortalID = categoryPortalID;
			this.Name = categoryName;
			this.Title = categoryTitle;
			this.ShortDescription = categoryShortDescription;
			this.Description = categoryDescription;
			this.ParentCategoryID = categoryParentCategoryID;
			this.DisplayOrder = categoryDisplayOrder;
			this.ImageFile = categoryImageFile;
			this.VisibleInd = categoryVisibleInd;
			this.SubCategoryGridVisibleInd = categorySubCategoryGridVisibleInd;
			this.SEOTitle = categorySEOTitle;
			this.SEOKeywords = categorySEOKeywords;
			this.SEODescription = categorySEODescription;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Category"/> instance.
		///</summary>
		///<param name="categoryPortalID"></param>
		///<param name="categoryName"></param>
		///<param name="categoryTitle"></param>
		///<param name="categoryShortDescription"></param>
		///<param name="categoryDescription"></param>
		///<param name="categoryParentCategoryID"></param>
		///<param name="categoryDisplayOrder"></param>
		///<param name="categoryImageFile"></param>
		///<param name="categoryVisibleInd"></param>
		///<param name="categorySubCategoryGridVisibleInd"></param>
		///<param name="categorySEOTitle"></param>
		///<param name="categorySEOKeywords"></param>
		///<param name="categorySEODescription"></param>
		public static Category CreateCategory(System.Int32 categoryPortalID, System.String categoryName, System.String categoryTitle, 
			System.String categoryShortDescription, System.String categoryDescription, System.Int32? categoryParentCategoryID, 
			System.Int32 categoryDisplayOrder, System.String categoryImageFile, System.Boolean categoryVisibleInd, 
			System.Boolean categorySubCategoryGridVisibleInd, System.String categorySEOTitle, System.String categorySEOKeywords, 
			System.String categorySEODescription)
		{
			Category newCategory = new Category();
			newCategory.PortalID = categoryPortalID;
			newCategory.Name = categoryName;
			newCategory.Title = categoryTitle;
			newCategory.ShortDescription = categoryShortDescription;
			newCategory.Description = categoryDescription;
			newCategory.ParentCategoryID = categoryParentCategoryID;
			newCategory.DisplayOrder = categoryDisplayOrder;
			newCategory.ImageFile = categoryImageFile;
			newCategory.VisibleInd = categoryVisibleInd;
			newCategory.SubCategoryGridVisibleInd = categorySubCategoryGridVisibleInd;
			newCategory.SEOTitle = categorySEOTitle;
			newCategory.SEOKeywords = categorySEOKeywords;
			newCategory.SEODescription = categorySEODescription;
			return newCategory;
		}
				
		#endregion Constructors
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoryColumn"/> which has raised the event.</param>
		public void OnColumnChanging(CategoryColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoryColumn"/> which has raised the event.</param>
		public void OnColumnChanged(CategoryColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(CategoryColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added)
				EntityManager.StopTracking(EntityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CategoryEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CategoryEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CategoryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(CategoryColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CategoryEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CategoryEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
				
		#region Properties	
				
		/// <summary>
		/// 	Gets or sets the CategoryID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 CategoryID
		{
			get
			{
				return this.entityData.CategoryID; 
			}
			
			set
			{
				if (this.entityData.CategoryID == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.CategoryID, this.entityData.CategoryID);
				this.entityData.CategoryID = value;
				this.EntityId.CategoryID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.CategoryID, this.entityData.CategoryID);
				OnPropertyChanged("CategoryID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PortalID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 PortalID
		{
			get
			{
				return this.entityData.PortalID; 
			}
			
			set
			{
				if (this.entityData.PortalID == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.PortalID, this.entityData.PortalID);
				this.entityData.PortalID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.PortalID, this.entityData.PortalID);
				OnPropertyChanged("PortalID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.String Name
		{
			get
			{
				return this.entityData.Name; 
			}
			
			set
			{
				if (this.entityData.Name == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.Name, this.entityData.Name);
				this.entityData.Name = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.Name, this.entityData.Name);
				OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Title property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String Title
		{
			get
			{
				return this.entityData.Title; 
			}
			
			set
			{
				if (this.entityData.Title == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.Title, this.entityData.Title);
				this.entityData.Title = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.Title, this.entityData.Title);
				OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ShortDescription property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String ShortDescription
		{
			get
			{
				return this.entityData.ShortDescription; 
			}
			
			set
			{
				if (this.entityData.ShortDescription == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.ShortDescription, this.entityData.ShortDescription);
				this.entityData.ShortDescription = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.ShortDescription, this.entityData.ShortDescription);
				OnPropertyChanged("ShortDescription");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is ntext.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ParentCategoryID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsParentCategoryIDNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ParentCategoryID
		{
			get
			{
				return this.entityData.ParentCategoryID; 
			}
			
			set
			{
				if (this.entityData.ParentCategoryID == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.ParentCategoryID, this.entityData.ParentCategoryID);
				this.entityData.ParentCategoryID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.ParentCategoryID, this.entityData.ParentCategoryID);
				OnPropertyChanged("ParentCategoryID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DisplayOrder property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 DisplayOrder
		{
			get
			{
				return this.entityData.DisplayOrder; 
			}
			
			set
			{
				if (this.entityData.DisplayOrder == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.DisplayOrder, this.entityData.DisplayOrder);
				this.entityData.DisplayOrder = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.DisplayOrder, this.entityData.DisplayOrder);
				OnPropertyChanged("DisplayOrder");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ImageFile property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String ImageFile
		{
			get
			{
				return this.entityData.ImageFile; 
			}
			
			set
			{
				if (this.entityData.ImageFile == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.ImageFile, this.entityData.ImageFile);
				this.entityData.ImageFile = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.ImageFile, this.entityData.ImageFile);
				OnPropertyChanged("ImageFile");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the VisibleInd property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean VisibleInd
		{
			get
			{
				return this.entityData.VisibleInd; 
			}
			
			set
			{
				if (this.entityData.VisibleInd == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.VisibleInd, this.entityData.VisibleInd);
				this.entityData.VisibleInd = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.VisibleInd, this.entityData.VisibleInd);
				OnPropertyChanged("VisibleInd");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SubCategoryGridVisibleInd property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean SubCategoryGridVisibleInd
		{
			get
			{
				return this.entityData.SubCategoryGridVisibleInd; 
			}
			
			set
			{
				if (this.entityData.SubCategoryGridVisibleInd == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.SubCategoryGridVisibleInd, this.entityData.SubCategoryGridVisibleInd);
				this.entityData.SubCategoryGridVisibleInd = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.SubCategoryGridVisibleInd, this.entityData.SubCategoryGridVisibleInd);
				OnPropertyChanged("SubCategoryGridVisibleInd");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SEOTitle property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String SEOTitle
		{
			get
			{
				return this.entityData.SEOTitle; 
			}
			
			set
			{
				if (this.entityData.SEOTitle == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.SEOTitle, this.entityData.SEOTitle);
				this.entityData.SEOTitle = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.SEOTitle, this.entityData.SEOTitle);
				OnPropertyChanged("SEOTitle");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SEOKeywords property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String SEOKeywords
		{
			get
			{
				return this.entityData.SEOKeywords; 
			}
			
			set
			{
				if (this.entityData.SEOKeywords == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.SEOKeywords, this.entityData.SEOKeywords);
				this.entityData.SEOKeywords = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.SEOKeywords, this.entityData.SEOKeywords);
				OnPropertyChanged("SEOKeywords");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SEODescription property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String SEODescription
		{
			get
			{
				return this.entityData.SEODescription; 
			}
			
			set
			{
				if (this.entityData.SEODescription == value)
					return;
					
					
				OnColumnChanging(CategoryColumn.SEODescription, this.entityData.SEODescription);
				this.entityData.SEODescription = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CategoryColumn.SEODescription, this.entityData.SEODescription);
				OnPropertyChanged("SEODescription");
			}
		}
		

		#region Source Foreign Key Property
				
		private Portal _portalIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Portal"/>.
		/// </summary>
		/// <value>The source Portal for PortalID.</value>
        [XmlIgnore()]
		[Browsable(false), BindableAttribute()]
		public virtual Portal PortalIDSource
      	{
            get { return this._portalIDSource; }
            set { this._portalIDSource = value; }
      	}
		private Category _parentCategoryIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Category"/>.
		/// </summary>
		/// <value>The source Category for ParentCategoryID.</value>
        [XmlIgnore()]
		[Browsable(false), BindableAttribute()]
		public virtual Category ParentCategoryIDSource
      	{
            get { return this._parentCategoryIDSource; }
            set { this._parentCategoryIDSource = value; }
      	}
		#endregion
			
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ZNodeCategory"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CategoryID", "PortalID", "Name", "Title", "ShortDescription", "Description", "ParentCategoryID", "DisplayOrder", "ImageFile", "VisibleInd", "SubCategoryGridVisibleInd", "SEOTitle", "SEOKeywords", "SEODescription"};
			}
		}
		#endregion 
		
	
		/// <summary>
		///	Holds a collection of ProductCategory objects
		///	which are related to this object through the relation FK_SC_ProductCategory_SC_Category
		/// </summary>	
		[BindableAttribute()]
		public TList<ProductCategory> ProductCategoryCollection
		{
			get { return entityData.ProductCategoryCollection; }
			set { entityData.ProductCategoryCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Category objects
		///	which are related to this object through the relation FK_SC_Category_SC_Category
		/// </summary>	
		[BindableAttribute()]
		public TList<Category> CategoryCollection
		{
			get { return entityData.CategoryCollection; }
			set { entityData.CategoryCollection = value; }	
		}
		
		#endregion
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CategoryEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Category) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return (object)this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Category>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Category);
	        }
	    }


		#endregion
		
		#region Methods	
			
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();
		}	
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Category Entity 
		///</summary>
		public virtual Category Copy()
		{
			//shallow copy entity
			Category copy = new Category();
			copy.CategoryID = this.CategoryID;
			copy.PortalID = this.PortalID;
			copy.Name = this.Name;
			copy.Title = this.Title;
			copy.ShortDescription = this.ShortDescription;
			copy.Description = this.Description;
			copy.ParentCategoryID = this.ParentCategoryID;
			copy.DisplayOrder = this.DisplayOrder;
			copy.ImageFile = this.ImageFile;
			copy.VisibleInd = this.VisibleInd;
			copy.SubCategoryGridVisibleInd = this.SubCategoryGridVisibleInd;
			copy.SEOTitle = this.SEOTitle;
			copy.SEOKeywords = this.SEOKeywords;
			copy.SEODescription = this.SEODescription;
					
			copy.AcceptChanges();
			return (Category)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Category Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Category DeepCopy()
		{
			return EntityHelper.Clone<Category>(this as Category);	
		}
		#endregion
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CategoryBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CategoryBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="CategoryBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="CategoryBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CategoryBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(CategoryBase Object1, CategoryBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CategoryID != Object2.CategoryID)
				equal = false;
			if (Object1.PortalID != Object2.PortalID)
				equal = false;
			if (Object1.Name != Object2.Name)
				equal = false;
			if ( Object1.Title != null && Object2.Title != null )
			{
				if (Object1.Title != Object2.Title)
					equal = false;
			}
			else if (Object1.Title == null ^ Object2.Title == null )
			{
				equal = false;
			}
			if ( Object1.ShortDescription != null && Object2.ShortDescription != null )
			{
				if (Object1.ShortDescription != Object2.ShortDescription)
					equal = false;
			}
			else if (Object1.ShortDescription == null ^ Object2.ShortDescription == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.ParentCategoryID != null && Object2.ParentCategoryID != null )
			{
				if (Object1.ParentCategoryID != Object2.ParentCategoryID)
					equal = false;
			}
			else if (Object1.ParentCategoryID == null ^ Object2.ParentCategoryID == null )
			{
				equal = false;
			}
			if (Object1.DisplayOrder != Object2.DisplayOrder)
				equal = false;
			if ( Object1.ImageFile != null && Object2.ImageFile != null )
			{
				if (Object1.ImageFile != Object2.ImageFile)
					equal = false;
			}
			else if (Object1.ImageFile == null ^ Object2.ImageFile == null )
			{
				equal = false;
			}
			if (Object1.VisibleInd != Object2.VisibleInd)
				equal = false;
			if (Object1.SubCategoryGridVisibleInd != Object2.SubCategoryGridVisibleInd)
				equal = false;
			if ( Object1.SEOTitle != null && Object2.SEOTitle != null )
			{
				if (Object1.SEOTitle != Object2.SEOTitle)
					equal = false;
			}
			else if (Object1.SEOTitle == null ^ Object2.SEOTitle == null )
			{
				equal = false;
			}
			if ( Object1.SEOKeywords != null && Object2.SEOKeywords != null )
			{
				if (Object1.SEOKeywords != Object2.SEOKeywords)
					equal = false;
			}
			else if (Object1.SEOKeywords == null ^ Object2.SEOKeywords == null )
			{
				equal = false;
			}
			if ( Object1.SEODescription != null && Object2.SEODescription != null )
			{
				if (Object1.SEODescription != Object2.SEODescription)
					equal = false;
			}
			else if (Object1.SEODescription == null ^ Object2.SEODescription == null )
			{
				equal = false;
			}
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			// TODO -> generate a strongly typed IComparer in the concrete class
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name) .CompareTo(((CategoryBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name));
		}
		
		/*
		// static method to get a Comparer object
        public static CategoryComparer GetComparer()
        {
            return new CategoryComparer();
        }
        */

        // Comparer delegates back to Category
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Category rhs, CategoryColumn which)
        {
            switch (which)
            {
            	
            	
            	case CategoryColumn.CategoryID:
            		return this.CategoryID.CompareTo(rhs.CategoryID);
            		
            		                 
            	
            	
            	case CategoryColumn.PortalID:
            		return this.PortalID.CompareTo(rhs.PortalID);
            		
            		                 
            	
            	
            	case CategoryColumn.Name:
            		return this.Name.CompareTo(rhs.Name);
            		
            		                 
            	
            	
            	case CategoryColumn.Title:
            		return this.Title.CompareTo(rhs.Title);
            		
            		                 
            	
            	
            	case CategoryColumn.ShortDescription:
            		return this.ShortDescription.CompareTo(rhs.ShortDescription);
            		
            		                 
            	
            	
            	case CategoryColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case CategoryColumn.ParentCategoryID:
            		return this.ParentCategoryID.Value.CompareTo(rhs.ParentCategoryID.Value);
            		
            		                 
            	
            	
            	case CategoryColumn.DisplayOrder:
            		return this.DisplayOrder.CompareTo(rhs.DisplayOrder);
            		
            		                 
            	
            	
            	case CategoryColumn.ImageFile:
            		return this.ImageFile.CompareTo(rhs.ImageFile);
            		
            		                 
            	
            	
            	case CategoryColumn.VisibleInd:
            		return this.VisibleInd.CompareTo(rhs.VisibleInd);
            		
            		                 
            	
            	
            	case CategoryColumn.SubCategoryGridVisibleInd:
            		return this.SubCategoryGridVisibleInd.CompareTo(rhs.SubCategoryGridVisibleInd);
            		
            		                 
            	
            	
            	case CategoryColumn.SEOTitle:
            		return this.SEOTitle.CompareTo(rhs.SEOTitle);
            		
            		                 
            	
            	
            	case CategoryColumn.SEOKeywords:
            		return this.SEOKeywords.CompareTo(rhs.SEOKeywords);
            		
            		                 
            	
            	
            	case CategoryColumn.SEODescription:
            		return this.SEODescription.CompareTo(rhs.SEODescription);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CategoryKey> Members
		
		// member variable for the EntityId property
		private CategoryKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public CategoryKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CategoryKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = @"Category" 
					+ this.CategoryID.ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{15}{14}- CategoryID: {0}{14}- PortalID: {1}{14}- Name: {2}{14}- Title: {3}{14}- ShortDescription: {4}{14}- Description: {5}{14}- ParentCategoryID: {6}{14}- DisplayOrder: {7}{14}- ImageFile: {8}{14}- VisibleInd: {9}{14}- SubCategoryGridVisibleInd: {10}{14}- SEOTitle: {11}{14}- SEOKeywords: {12}{14}- SEODescription: {13}{14}", 
				this.CategoryID,
				this.PortalID,
				this.Name,
				(this.Title == null) ? string.Empty : this.Title.ToString(),
				(this.ShortDescription == null) ? string.Empty : this.ShortDescription.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.ParentCategoryID == null) ? string.Empty : this.ParentCategoryID.ToString(),
				this.DisplayOrder,
				(this.ImageFile == null) ? string.Empty : this.ImageFile.ToString(),
				this.VisibleInd,
				this.SubCategoryGridVisibleInd,
				(this.SEOTitle == null) ? string.Empty : this.SEOTitle.ToString(),
				(this.SEOKeywords == null) ? string.Empty : this.SEOKeywords.ToString(),
				(this.SEODescription == null) ? string.Empty : this.SEODescription.ToString(),
				Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ZNodeCategory' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal class CategoryEntityData : ICloneable
	{
		#region Variable Declarations
		
		#region Primary key(s)
			/// <summary>			
			/// CategoryID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "ZNodeCategory"</remarks>
			public System.Int32 CategoryID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// PortalID : 
		/// </summary>
		public System.Int32		  PortalID = (int)0;
		
		/// <summary>
		/// Name : 
		/// </summary>
		public System.String		  Name = string.Empty;
		
		/// <summary>
		/// Title : 
		/// </summary>
		public System.String		  Title = string.Empty;
		
		/// <summary>
		/// ShortDescription : 
		/// </summary>
		public System.String		  ShortDescription = string.Empty;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String		  Description = string.Empty;
		
		/// <summary>
		/// ParentCategoryID : 
		/// </summary>
		public System.Int32?		  ParentCategoryID = (int)0;
		
		/// <summary>
		/// DisplayOrder : 
		/// </summary>
		public System.Int32		  DisplayOrder = (int)0;
		
		/// <summary>
		/// ImageFile : 
		/// </summary>
		public System.String		  ImageFile = string.Empty;
		
		/// <summary>
		/// VisibleInd : 
		/// </summary>
		public System.Boolean		  VisibleInd = false;
		
		/// <summary>
		/// SubCategoryGridVisibleInd : 
		/// </summary>
		public System.Boolean		  SubCategoryGridVisibleInd = false;
		
		/// <summary>
		/// SEOTitle : 
		/// </summary>
		public System.String		  SEOTitle = string.Empty;
		
		/// <summary>
		/// SEOKeywords : 
		/// </summary>
		public System.String		  SEOKeywords = string.Empty;
		
		/// <summary>
		/// SEODescription : 
		/// </summary>
		public System.String		  SEODescription = string.Empty;
		#endregion
			
		#endregion Variable Declarations
		
		#region Clone
		public Object Clone()
		{
			CategoryEntityData _tmp = new CategoryEntityData();
						
			_tmp.CategoryID = this.CategoryID;
			
			_tmp.PortalID = this.PortalID;
			_tmp.Name = this.Name;
			_tmp.Title = this.Title;
			_tmp.ShortDescription = this.ShortDescription;
			_tmp.Description = this.Description;
			_tmp.ParentCategoryID = this.ParentCategoryID;
			_tmp.DisplayOrder = this.DisplayOrder;
			_tmp.ImageFile = this.ImageFile;
			_tmp.VisibleInd = this.VisibleInd;
			_tmp.SubCategoryGridVisibleInd = this.SubCategoryGridVisibleInd;
			_tmp.SEOTitle = this.SEOTitle;
			_tmp.SEOKeywords = this.SEOKeywords;
			_tmp.SEODescription = this.SEODescription;
			
			return _tmp;
		}
		#endregion 
		
		#region Data Properties

		#region ProductCategoryCollection
		
		private TList<ProductCategory> productCategoryCategoryID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation productCategoryCategoryID
		/// </summary>	
		public TList<ProductCategory> ProductCategoryCollection
		{
			get
			{
				if (productCategoryCategoryID == null)
				{
				productCategoryCategoryID = new TList<ProductCategory>();
				}
	
				return productCategoryCategoryID;
			}
			set { productCategoryCategoryID = value; }
		}
		
		#endregion

		#region CategoryCollection
		
		private TList<Category> categoryParentCategoryID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation categoryParentCategoryID
		/// </summary>	
		public TList<Category> CategoryCollection
		{
			get
			{
				if (categoryParentCategoryID == null)
				{
				categoryParentCategoryID = new TList<Category>();
				}
	
				return categoryParentCategoryID;
			}
			set { categoryParentCategoryID = value; }
		}
		
		#endregion

		#endregion Data Properties

	}//End struct


		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(Validation.CommonRules.NotNull,"Name");
		}
   		#endregion
	
	} // End Class
	
	#region CategoryComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CategoryComparer : System.Collections.Generic.IComparer<Category>
	{
		CategoryColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CategoryComparer"/> class.
        /// </summary>
		public CategoryComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:%=className%>Comparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CategoryComparer(CategoryColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Category"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Category"/> to compare.</param>
        /// <param name="b">The second <c>Category</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Category a, Category b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Category entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Category a, Category b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CategoryColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CategoryKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Category"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CategoryKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CategoryKey class.
		/// </summary>
		public CategoryKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CategoryKey class.
		/// </summary>
		public CategoryKey(CategoryBase entity)
		{
			Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.categoryID = entity.CategoryID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CategoryKey class.
		/// </summary>
		public CategoryKey(System.Int32 categoryID)
		{
			#region Init Properties

			this.categoryID = categoryID;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CategoryBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CategoryBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CategoryID property
		private System.Int32 categoryID;
		
		/// <summary>
		/// Gets or sets the CategoryID property.
		/// </summary>
		public System.Int32 CategoryID
		{
			get { return categoryID; }
			set
			{
				if ( Entity != null )
				{
					Entity.CategoryID = value;
				}
				
				categoryID = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CategoryID = ( values["CategoryID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CategoryID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CategoryID", CategoryID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CategoryID: {0}{1}",
								CategoryID,
								Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CategoryColumn Enum
	
	/// <summary>
	/// Enumerate the Category columns.
	/// </summary>
	[Serializable]
	public enum CategoryColumn : int
	{
		/// <summary>
		/// CategoryID : 
		/// </summary>
		[EnumTextValue("CategoryID")]
		[ColumnEnum("CategoryID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		CategoryID = 1,
		/// <summary>
		/// PortalID : 
		/// </summary>
		[EnumTextValue("PortalID")]
		[ColumnEnum("PortalID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		PortalID = 2,
		/// <summary>
		/// Name : 
		/// </summary>
		[EnumTextValue("Name")]
		[ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, false)]
		Name = 3,
		/// <summary>
		/// Title : 
		/// </summary>
		[EnumTextValue("Title")]
		[ColumnEnum("Title", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Title = 4,
		/// <summary>
		/// ShortDescription : 
		/// </summary>
		[EnumTextValue("ShortDescription")]
		[ColumnEnum("ShortDescription", typeof(System.String), System.Data.DbType.String, false, false, true)]
		ShortDescription = 5,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true)]
		Description = 6,
		/// <summary>
		/// ParentCategoryID : 
		/// </summary>
		[EnumTextValue("ParentCategoryID")]
		[ColumnEnum("ParentCategoryID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ParentCategoryID = 7,
		/// <summary>
		/// DisplayOrder : 
		/// </summary>
		[EnumTextValue("DisplayOrder")]
		[ColumnEnum("DisplayOrder", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		DisplayOrder = 8,
		/// <summary>
		/// ImageFile : 
		/// </summary>
		[EnumTextValue("ImageFile")]
		[ColumnEnum("ImageFile", typeof(System.String), System.Data.DbType.String, false, false, true)]
		ImageFile = 9,
		/// <summary>
		/// VisibleInd : 
		/// </summary>
		[EnumTextValue("VisibleInd")]
		[ColumnEnum("VisibleInd", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		VisibleInd = 10,
		/// <summary>
		/// SubCategoryGridVisibleInd : 
		/// </summary>
		[EnumTextValue("SubCategoryGridVisibleInd")]
		[ColumnEnum("SubCategoryGridVisibleInd", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		SubCategoryGridVisibleInd = 11,
		/// <summary>
		/// SEOTitle : 
		/// </summary>
		[EnumTextValue("SEOTitle")]
		[ColumnEnum("SEOTitle", typeof(System.String), System.Data.DbType.String, false, false, true)]
		SEOTitle = 12,
		/// <summary>
		/// SEOKeywords : 
		/// </summary>
		[EnumTextValue("SEOKeywords")]
		[ColumnEnum("SEOKeywords", typeof(System.String), System.Data.DbType.String, false, false, true)]
		SEOKeywords = 13,
		/// <summary>
		/// SEODescription : 
		/// </summary>
		[EnumTextValue("SEODescription")]
		[ColumnEnum("SEODescription", typeof(System.String), System.Data.DbType.String, false, false, true)]
		SEODescription = 14
	}//End enum

	#endregion CategoryColumn Enum

} // end namespace
