	
/*
	File generated by NetTiers templates [www.nettiers.com]
	Generated on : Thursday, October 18, 2007
	Important: Do not modify this file. Edit the file Coupon.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace ZNode.Libraries.DataAccess.Entities
{
	#region CouponEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Coupon"/> object.
	/// </remarks>
	public class CouponEventArgs : System.EventArgs
	{
		private CouponColumn column;
		private object value;
		
		
		///<summary>
		/// Initalizes a new Instance of the CouponEventArgs class.
		///</summary>
		public CouponEventArgs(CouponColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CouponEventArgs class.
		///</summary>
		public CouponEventArgs(CouponColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		
		///<summary>
		/// The CouponColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CouponColumn" />
		public CouponColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	
	///<summary>
	/// Define a delegate for all Coupon related events.
	///</summary>
	public delegate void CouponEventHandler(object sender, CouponEventArgs e);
	
	///<summary>
	/// An object representation of the 'ZNodeCoupon' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	//[ToolboxItem(typeof(Coupon))]
	public abstract partial class CouponBase : EntityBase, IEntityId<CouponKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		/// 	Old the inner data of the entity.
		/// </summary>
		private CouponEntityData entityData;
		
		// <summary>
		// 	Old the original data of the entity.
		// </summary>
		//CouponEntityData originalData;
		
		/// <summary>
		/// 	Old a backup of the inner data of the entity.
		/// </summary>
		private CouponEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		[NonSerialized]
		private TList<Coupon> parentCollection;
		private bool inTxn = false;

		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event CouponEventHandler ColumnChanging;
		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CouponEventHandler ColumnChanged;		
		#endregion "Variable Declarations"
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CouponBase"/> instance.
		///</summary>
		public CouponBase()
		{
			this.entityData = new CouponEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CouponBase"/> instance.
		///</summary>
		///<param name="couponCouponCode"></param>
		///<param name="couponDiscount"></param>
		///<param name="couponDiscountTypeID"></param>
		///<param name="couponDiscountTargetID"></param>
		///<param name="couponStartDate"></param>
		///<param name="couponExpDate"></param>
		///<param name="couponQuantityAvailable"></param>
		///<param name="couponProductList"></param>
		///<param name="couponOrderMinimum"></param>
		public CouponBase(System.String couponCouponCode, System.Decimal couponDiscount, System.Int32 couponDiscountTypeID, 
			System.Int32 couponDiscountTargetID, System.DateTime couponStartDate, System.DateTime couponExpDate, System.Int32 couponQuantityAvailable, 
			System.String couponProductList, System.Decimal couponOrderMinimum)
		{
			this.entityData = new CouponEntityData();
			this.backupData = null;

			this.CouponCode = couponCouponCode;
			this.Discount = couponDiscount;
			this.DiscountTypeID = couponDiscountTypeID;
			this.DiscountTargetID = couponDiscountTargetID;
			this.StartDate = couponStartDate;
			this.ExpDate = couponExpDate;
			this.QuantityAvailable = couponQuantityAvailable;
			this.ProductList = couponProductList;
			this.OrderMinimum = couponOrderMinimum;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Coupon"/> instance.
		///</summary>
		///<param name="couponCouponCode"></param>
		///<param name="couponDiscount"></param>
		///<param name="couponDiscountTypeID"></param>
		///<param name="couponDiscountTargetID"></param>
		///<param name="couponStartDate"></param>
		///<param name="couponExpDate"></param>
		///<param name="couponQuantityAvailable"></param>
		///<param name="couponProductList"></param>
		///<param name="couponOrderMinimum"></param>
		public static Coupon CreateCoupon(System.String couponCouponCode, System.Decimal couponDiscount, System.Int32 couponDiscountTypeID, 
			System.Int32 couponDiscountTargetID, System.DateTime couponStartDate, System.DateTime couponExpDate, System.Int32 couponQuantityAvailable, 
			System.String couponProductList, System.Decimal couponOrderMinimum)
		{
			Coupon newCoupon = new Coupon();
			newCoupon.CouponCode = couponCouponCode;
			newCoupon.Discount = couponDiscount;
			newCoupon.DiscountTypeID = couponDiscountTypeID;
			newCoupon.DiscountTargetID = couponDiscountTargetID;
			newCoupon.StartDate = couponStartDate;
			newCoupon.ExpDate = couponExpDate;
			newCoupon.QuantityAvailable = couponQuantityAvailable;
			newCoupon.ProductList = couponProductList;
			newCoupon.OrderMinimum = couponOrderMinimum;
			return newCoupon;
		}
				
		#endregion Constructors
		
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CouponColumn"/> which has raised the event.</param>
		public void OnColumnChanging(CouponColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CouponColumn"/> which has raised the event.</param>
		public void OnColumnChanged(CouponColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CouponColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(CouponColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added)
				EntityManager.StopTracking(EntityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CouponEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CouponEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CouponColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(CouponColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CouponEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CouponEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
				
		#region Properties	
				
		/// <summary>
		/// 	Gets or sets the CouponID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 CouponID
		{
			get
			{
				return this.entityData.CouponID; 
			}
			
			set
			{
				if (this.entityData.CouponID == value)
					return;
					
					
				OnColumnChanging(CouponColumn.CouponID, this.entityData.CouponID);
				this.entityData.CouponID = value;
				this.EntityId.CouponID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.CouponID, this.entityData.CouponID);
				OnPropertyChanged("CouponID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CouponCode property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false, 100)]
		public virtual System.String CouponCode
		{
			get
			{
				return this.entityData.CouponCode; 
			}
			
			set
			{
				if (this.entityData.CouponCode == value)
					return;
					
					
				OnColumnChanging(CouponColumn.CouponCode, this.entityData.CouponCode);
				this.entityData.CouponCode = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.CouponCode, this.entityData.CouponCode);
				OnPropertyChanged("CouponCode");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Discount property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Decimal Discount
		{
			get
			{
				return this.entityData.Discount; 
			}
			
			set
			{
				if (this.entityData.Discount == value)
					return;
					
					
				OnColumnChanging(CouponColumn.Discount, this.entityData.Discount);
				this.entityData.Discount = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.Discount, this.entityData.Discount);
				OnPropertyChanged("Discount");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DiscountTypeID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 DiscountTypeID
		{
			get
			{
				return this.entityData.DiscountTypeID; 
			}
			
			set
			{
				if (this.entityData.DiscountTypeID == value)
					return;
					
					
				OnColumnChanging(CouponColumn.DiscountTypeID, this.entityData.DiscountTypeID);
				this.entityData.DiscountTypeID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.DiscountTypeID, this.entityData.DiscountTypeID);
				OnPropertyChanged("DiscountTypeID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DiscountTargetID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 DiscountTargetID
		{
			get
			{
				return this.entityData.DiscountTargetID; 
			}
			
			set
			{
				if (this.entityData.DiscountTargetID == value)
					return;
					
					
				OnColumnChanging(CouponColumn.DiscountTargetID, this.entityData.DiscountTargetID);
				this.entityData.DiscountTargetID = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.DiscountTargetID, this.entityData.DiscountTargetID);
				OnPropertyChanged("DiscountTargetID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the StartDate property. 
		///		
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime StartDate
		{
			get
			{
				return this.entityData.StartDate; 
			}
			
			set
			{
				if (this.entityData.StartDate == value)
					return;
					
					
				OnColumnChanging(CouponColumn.StartDate, this.entityData.StartDate);
				this.entityData.StartDate = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.StartDate, this.entityData.StartDate);
				OnPropertyChanged("StartDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ExpDate property. 
		///		
		/// </summary>
		/// <value>This type is smalldatetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime ExpDate
		{
			get
			{
				return this.entityData.ExpDate; 
			}
			
			set
			{
				if (this.entityData.ExpDate == value)
					return;
					
					
				OnColumnChanging(CouponColumn.ExpDate, this.entityData.ExpDate);
				this.entityData.ExpDate = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.ExpDate, this.entityData.ExpDate);
				OnPropertyChanged("ExpDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the QuantityAvailable property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 QuantityAvailable
		{
			get
			{
				return this.entityData.QuantityAvailable; 
			}
			
			set
			{
				if (this.entityData.QuantityAvailable == value)
					return;
					
					
				OnColumnChanging(CouponColumn.QuantityAvailable, this.entityData.QuantityAvailable);
				this.entityData.QuantityAvailable = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.QuantityAvailable, this.entityData.QuantityAvailable);
				OnPropertyChanged("QuantityAvailable");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ProductList property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, true)]
		public virtual System.String ProductList
		{
			get
			{
				return this.entityData.ProductList; 
			}
			
			set
			{
				if (this.entityData.ProductList == value)
					return;
					
					
				OnColumnChanging(CouponColumn.ProductList, this.entityData.ProductList);
				this.entityData.ProductList = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.ProductList, this.entityData.ProductList);
				OnPropertyChanged("ProductList");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the OrderMinimum property. 
		///		
		/// </summary>
		/// <value>This type is money.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), BindableAttribute()]
		[DataObjectField(false, false, false)]
		public virtual System.Decimal OrderMinimum
		{
			get
			{
				return this.entityData.OrderMinimum; 
			}
			
			set
			{
				if (this.entityData.OrderMinimum == value)
					return;
					
					
				OnColumnChanging(CouponColumn.OrderMinimum, this.entityData.OrderMinimum);
				this.entityData.OrderMinimum = value;
				if (this.EntityState == EntityState.Unchanged)
				{
					this.EntityState = EntityState.Changed;
				}
				OnColumnChanged(CouponColumn.OrderMinimum, this.entityData.OrderMinimum);
				OnPropertyChanged("OrderMinimum");
			}
		}
		

		#region Source Foreign Key Property
				
		private DiscountTarget _discountTargetIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="DiscountTarget"/>.
		/// </summary>
		/// <value>The source DiscountTarget for DiscountTargetID.</value>
        [XmlIgnore()]
		[Browsable(false), BindableAttribute()]
		public virtual DiscountTarget DiscountTargetIDSource
      	{
            get { return this._discountTargetIDSource; }
            set { this._discountTargetIDSource = value; }
      	}
		private DiscountType _discountTypeIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="DiscountType"/>.
		/// </summary>
		/// <value>The source DiscountType for DiscountTypeID.</value>
        [XmlIgnore()]
		[Browsable(false), BindableAttribute()]
		public virtual DiscountType DiscountTypeIDSource
      	{
            get { return this._discountTypeIDSource; }
            set { this._discountTypeIDSource = value; }
      	}
		#endregion
			
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ZNodeCoupon"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CouponID", "CouponCode", "Discount", "DiscountTypeID", "DiscountTargetID", "StartDate", "ExpDate", "QuantityAvailable", "ProductList", "OrderMinimum"};
			}
		}
		#endregion 
		
	
		/// <summary>
		///	Holds a collection of Order objects
		///	which are related to this object through the relation FK_ZNodeOrder_ZNodeCoupon
		/// </summary>	
		[BindableAttribute()]
		public TList<Order> OrderCollection
		{
			get { return entityData.OrderCollection; }
			set { entityData.OrderCollection = value; }	
		}
		
		#endregion
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CouponEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Coupon) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return (object)this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Coupon>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Coupon);
	        }
	    }


		#endregion
		
		#region Methods	
			
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();
		}	
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Coupon Entity 
		///</summary>
		public virtual Coupon Copy()
		{
			//shallow copy entity
			Coupon copy = new Coupon();
			copy.CouponID = this.CouponID;
			copy.CouponCode = this.CouponCode;
			copy.Discount = this.Discount;
			copy.DiscountTypeID = this.DiscountTypeID;
			copy.DiscountTargetID = this.DiscountTargetID;
			copy.StartDate = this.StartDate;
			copy.ExpDate = this.ExpDate;
			copy.QuantityAvailable = this.QuantityAvailable;
			copy.ProductList = this.ProductList;
			copy.OrderMinimum = this.OrderMinimum;
					
			copy.AcceptChanges();
			return (Coupon)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Coupon Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Coupon DeepCopy()
		{
			return EntityHelper.Clone<Coupon>(this as Coupon);	
		}
		#endregion
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CouponBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CouponBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="CouponBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="CouponBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CouponBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(CouponBase Object1, CouponBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CouponID != Object2.CouponID)
				equal = false;
			if (Object1.CouponCode != Object2.CouponCode)
				equal = false;
			if (Object1.Discount != Object2.Discount)
				equal = false;
			if (Object1.DiscountTypeID != Object2.DiscountTypeID)
				equal = false;
			if (Object1.DiscountTargetID != Object2.DiscountTargetID)
				equal = false;
			if (Object1.StartDate != Object2.StartDate)
				equal = false;
			if (Object1.ExpDate != Object2.ExpDate)
				equal = false;
			if (Object1.QuantityAvailable != Object2.QuantityAvailable)
				equal = false;
			if ( Object1.ProductList != null && Object2.ProductList != null )
			{
				if (Object1.ProductList != Object2.ProductList)
					equal = false;
			}
			else if (Object1.ProductList == null ^ Object2.ProductList == null )
			{
				equal = false;
			}
			if (Object1.OrderMinimum != Object2.OrderMinimum)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			// TODO -> generate a strongly typed IComparer in the concrete class
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name) .CompareTo(((CouponBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0].Name));
		}
		
		/*
		// static method to get a Comparer object
        public static CouponComparer GetComparer()
        {
            return new CouponComparer();
        }
        */

        // Comparer delegates back to Coupon
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Coupon rhs, CouponColumn which)
        {
            switch (which)
            {
            	
            	
            	case CouponColumn.CouponID:
            		return this.CouponID.CompareTo(rhs.CouponID);
            		
            		                 
            	
            	
            	case CouponColumn.CouponCode:
            		return this.CouponCode.CompareTo(rhs.CouponCode);
            		
            		                 
            	
            	
            	case CouponColumn.Discount:
            		return this.Discount.CompareTo(rhs.Discount);
            		
            		                 
            	
            	
            	case CouponColumn.DiscountTypeID:
            		return this.DiscountTypeID.CompareTo(rhs.DiscountTypeID);
            		
            		                 
            	
            	
            	case CouponColumn.DiscountTargetID:
            		return this.DiscountTargetID.CompareTo(rhs.DiscountTargetID);
            		
            		                 
            	
            	
            	case CouponColumn.StartDate:
            		return this.StartDate.CompareTo(rhs.StartDate);
            		
            		                 
            	
            	
            	case CouponColumn.ExpDate:
            		return this.ExpDate.CompareTo(rhs.ExpDate);
            		
            		                 
            	
            	
            	case CouponColumn.QuantityAvailable:
            		return this.QuantityAvailable.CompareTo(rhs.QuantityAvailable);
            		
            		                 
            	
            	
            	case CouponColumn.ProductList:
            		return this.ProductList.CompareTo(rhs.ProductList);
            		
            		                 
            	
            	
            	case CouponColumn.OrderMinimum:
            		return this.OrderMinimum.CompareTo(rhs.OrderMinimum);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CouponKey> Members
		
		// member variable for the EntityId property
		private CouponKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public CouponKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CouponKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = @"Coupon" 
					+ this.CouponID.ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{11}{10}- CouponID: {0}{10}- CouponCode: {1}{10}- Discount: {2}{10}- DiscountTypeID: {3}{10}- DiscountTargetID: {4}{10}- StartDate: {5}{10}- ExpDate: {6}{10}- QuantityAvailable: {7}{10}- ProductList: {8}{10}- OrderMinimum: {9}{10}", 
				this.CouponID,
				this.CouponCode,
				this.Discount,
				this.DiscountTypeID,
				this.DiscountTargetID,
				this.StartDate,
				this.ExpDate,
				this.QuantityAvailable,
				(this.ProductList == null) ? string.Empty : this.ProductList.ToString(),
				this.OrderMinimum,
				Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ZNodeCoupon' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal class CouponEntityData : ICloneable
	{
		#region Variable Declarations
		
		#region Primary key(s)
			/// <summary>			
			/// CouponID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "ZNodeCoupon"</remarks>
			public System.Int32 CouponID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// CouponCode : 
		/// </summary>
		public System.String		  CouponCode = string.Empty;
		
		/// <summary>
		/// Discount : 
		/// </summary>
		public System.Decimal		  Discount = 0.0m;
		
		/// <summary>
		/// DiscountTypeID : 
		/// </summary>
		public System.Int32		  DiscountTypeID = (int)0;
		
		/// <summary>
		/// DiscountTargetID : 
		/// </summary>
		public System.Int32		  DiscountTargetID = (int)0;
		
		/// <summary>
		/// StartDate : 
		/// </summary>
		public System.DateTime		  StartDate = DateTime.MinValue;
		
		/// <summary>
		/// ExpDate : 
		/// </summary>
		public System.DateTime		  ExpDate = DateTime.MinValue;
		
		/// <summary>
		/// QuantityAvailable : 
		/// </summary>
		public System.Int32		  QuantityAvailable = (int)0;
		
		/// <summary>
		/// ProductList : 
		/// </summary>
		public System.String		  ProductList = string.Empty;
		
		/// <summary>
		/// OrderMinimum : 
		/// </summary>
		public System.Decimal		  OrderMinimum = 0;
		#endregion
			
		#endregion Variable Declarations
		
		#region Clone
		public Object Clone()
		{
			CouponEntityData _tmp = new CouponEntityData();
						
			_tmp.CouponID = this.CouponID;
			
			_tmp.CouponCode = this.CouponCode;
			_tmp.Discount = this.Discount;
			_tmp.DiscountTypeID = this.DiscountTypeID;
			_tmp.DiscountTargetID = this.DiscountTargetID;
			_tmp.StartDate = this.StartDate;
			_tmp.ExpDate = this.ExpDate;
			_tmp.QuantityAvailable = this.QuantityAvailable;
			_tmp.ProductList = this.ProductList;
			_tmp.OrderMinimum = this.OrderMinimum;
			
			return _tmp;
		}
		#endregion 
		
		#region Data Properties

		#region OrderCollection
		
		private TList<Order> orderCouponID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation orderCouponID
		/// </summary>	
		public TList<Order> OrderCollection
		{
			get
			{
				if (orderCouponID == null)
				{
				orderCouponID = new TList<Order>();
				}
	
				return orderCouponID;
			}
			set { orderCouponID = value; }
		}
		
		#endregion

		#endregion Data Properties

	}//End struct


		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(Validation.CommonRules.NotNull,"CouponCode");
			ValidationRules.AddRule(Validation.CommonRules.StringMaxLength,new Validation.CommonRules.MaxLengthRuleArgs("CouponCode",100));
		}
   		#endregion
	
	} // End Class
	
	#region CouponComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CouponComparer : System.Collections.Generic.IComparer<Coupon>
	{
		CouponColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CouponComparer"/> class.
        /// </summary>
		public CouponComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:%=className%>Comparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CouponComparer(CouponColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Coupon"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Coupon"/> to compare.</param>
        /// <param name="b">The second <c>Coupon</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Coupon a, Coupon b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Coupon entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Coupon a, Coupon b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CouponColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CouponKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Coupon"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CouponKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CouponKey class.
		/// </summary>
		public CouponKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CouponKey class.
		/// </summary>
		public CouponKey(CouponBase entity)
		{
			Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.couponID = entity.CouponID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CouponKey class.
		/// </summary>
		public CouponKey(System.Int32 couponID)
		{
			#region Init Properties

			this.couponID = couponID;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CouponBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CouponBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CouponID property
		private System.Int32 couponID;
		
		/// <summary>
		/// Gets or sets the CouponID property.
		/// </summary>
		public System.Int32 CouponID
		{
			get { return couponID; }
			set
			{
				if ( Entity != null )
				{
					Entity.CouponID = value;
				}
				
				couponID = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CouponID = ( values["CouponID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CouponID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CouponID", CouponID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CouponID: {0}{1}",
								CouponID,
								Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CouponColumn Enum
	
	/// <summary>
	/// Enumerate the Coupon columns.
	/// </summary>
	[Serializable]
	public enum CouponColumn : int
	{
		/// <summary>
		/// CouponID : 
		/// </summary>
		[EnumTextValue("CouponID")]
		[ColumnEnum("CouponID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		CouponID = 1,
		/// <summary>
		/// CouponCode : 
		/// </summary>
		[EnumTextValue("CouponCode")]
		[ColumnEnum("CouponCode", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 100)]
		CouponCode = 2,
		/// <summary>
		/// Discount : 
		/// </summary>
		[EnumTextValue("Discount")]
		[ColumnEnum("Discount", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		Discount = 3,
		/// <summary>
		/// DiscountTypeID : 
		/// </summary>
		[EnumTextValue("DiscountTypeID")]
		[ColumnEnum("DiscountTypeID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		DiscountTypeID = 4,
		/// <summary>
		/// DiscountTargetID : 
		/// </summary>
		[EnumTextValue("DiscountTargetID")]
		[ColumnEnum("DiscountTargetID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		DiscountTargetID = 5,
		/// <summary>
		/// StartDate : 
		/// </summary>
		[EnumTextValue("StartDate")]
		[ColumnEnum("StartDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		StartDate = 6,
		/// <summary>
		/// ExpDate : 
		/// </summary>
		[EnumTextValue("ExpDate")]
		[ColumnEnum("ExpDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		ExpDate = 7,
		/// <summary>
		/// QuantityAvailable : 
		/// </summary>
		[EnumTextValue("QuantityAvailable")]
		[ColumnEnum("QuantityAvailable", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		QuantityAvailable = 8,
		/// <summary>
		/// ProductList : 
		/// </summary>
		[EnumTextValue("ProductList")]
		[ColumnEnum("ProductList", typeof(System.String), System.Data.DbType.AnsiString, false, false, true)]
		ProductList = 9,
		/// <summary>
		/// OrderMinimum : 
		/// </summary>
		[EnumTextValue("OrderMinimum")]
		[ColumnEnum("OrderMinimum", typeof(System.Decimal), System.Data.DbType.Currency, false, false, false)]
		OrderMinimum = 10
	}//End enum

	#endregion CouponColumn Enum

} // end namespace
